miniProgram:
  appid: wxb1cd5bc64dbc5980
  grantType: authorization_code
  loginUrl: https://api.weixin.qq.com/sns/jscode2session
  secret: 48b399b2902602f3eef7028c1826b33d
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
  accessTokenGrantType: client_credential
  getPhoneNumberUrl: https://api.weixin.qq.com/wxa/business/getuserphonenumber
  batchWithdrawUrl: https://api.mch.weixin.qq.com/v3/transfer/batches
  profitSharing:
    addUrl: https://api.mch.weixin.qq.com/v3/profitsharing/receivers/add
    dealUrl: https://api.mch.weixin.qq.com/v3/profitsharing/orders
    queryUrl: /v3/profitsharing/orders/

server:
  port: 80
xunfei:
  apiKey: 06c81b286fb9b05805871890ccdd0320
  apiSecret: ZjMxNjQ4ZGY5OTExYzRmZGE5ODExMjk5
  appid: d3fe4292
  hostUrl: https://spark-api.xf-yun.com/v3.5/chat


spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-fa05qacw.sql.tencentcdb.com:26944/springboot_demo
    username: root
    password: Xiaoe3504
    driver-class-name: com.mysql.cj.jdbc.Driver
  websocket:
      timeout: 30000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.psy.demo.dto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

baichuan:
  url:
    addAndQuery: https://api.baichuan-ai.com/v1/npc
    deleteAndUpdate: https://api.baichuan-ai.com/v1/npc/
    chat: https://api.baichuan-ai.com/v1/chat/completions
  appKey: Bearer sk-2a26618225a18d097302965e20204758

logging:
  file:
    name: app.log
  level:
    root: INFO